### ISSUE TITLE
Macro build order

### ISSUE THREAD

**Issue by ianharrigan** [profelis/bindx2#12]
Hi,

Thanks for the great lib - thinking about using it for haxeui, however, i _think_ im running into a macro build order issue and wondering what advice you might have about how to avoid it. Consider (there is a bit of noise here):

```haxe
class Component implements IBindable {
    public function new() {
    }
}

class Slider extends Component {
    @:bindable public var pos:Float = 0;
    
    public function new() {
        super();
    }
}

@:build(ComponentMacros.build())
class CustomComponent extends Component {
    public var theSlider:Slider = new Slider();
    
    @:bind(theSlider.pos) public var someValue:Float = 0;
    
    public function new() {
        super();
        
        Bind.bindTo(this.someValue, this.theSlider.pos);
        Bind.bindTo(this.theSlider.pos, this.someValue);
    }
 }
```

And the `ComponentMacros.build()` is pretty simple: 
```haxe
        var bindableFields = Macros.getFieldsWithMeta("bind", fields);
        for (f in bindableFields) {
            f.meta.push( { name: ":bindable", pos: pos, params: [] });
        }
```
In essence, what im trying to do is add the `:bindable` meta data as part of the macro (so that i can use my own `:bind(...)` meta to link things together. However, i get the error:

```
BindSignalProvider.hx:65: characters 42-59 : CustomComponent has no field someValueChanged
```
If i add the `@:bindable` meta on the `someVar` then everything is fine. Presumably because some part of the bindx macro system hasnt run yet? Do you have any advice on this?

Thanks in advance,
Ian

**Comment by profelis** [comment]
Hi!

Try to remove `IBindable` inheritance and add manually `@:build(bindx.macro.BindableMacros.buildIBindable())` where you need/want.

Btw, documentation is **very** specified for this case https://haxe.org/manual/macro-limitations-build-order.html

**Comment by ianharrigan** [comment]
Hey, thanks for the response - i figured it was a build order thing. Ive managed to get around it now with a few tweaks (hacks!) to the lib - thanks again!
