### ISSUE TITLE
Trouble with lazySignal

### ISSUE THREAD

**Issue by aartzrc** [profelis/bindx2#16]
Having some trouble understanding how to use lazySignal. My goal would be to have defaults in a class, and then use a Bind.bind() to automatically call initialization functions. Bind.notify works, but in a more complex application it could signal things I do not expect (or just be redundant).

I created a simple test below. Switching lazySignal true or false does not fire the boolChanged function either way. Maybe I misunderstand, any help is appreciated.

```
import bindx.*;

class Main implements IBindable {
    @:bindable(lazySignal = false)
    var someBool:Bool = false;

    static function main() {
        var m = new Main();

        Bind.notify(m.someBool, false, false); // notify can be used, but it would be great to have Bind.bind send a signal to the new listener only
    }

    function new() {
        Bind.bind(this.someBool, boolChanged); // Any way to make this signal/dispatch immediately?
    }

    function boolChanged(from:Bool, to:Bool) {
        trace("HERE");
    }
}
```

**Comment by profelis** [comment]
@aartzrc You can use extended api for this. Change `Bind.bind` to `BindExt.chain` and `boolChanged` will be called in first time automatically - https://github.com/profelis/bindx2#extended-api.

**Comment by aartzrc** [comment]
Great, that's what I was missing! So the lazySignal flag is for extended api use only?

Also something that I would like to discuss if you have time: I like to use BindAll sometimes, but if you re-use a listener function it gets difficult to manage many BindAll responses because you cannot tell what the signal source is. For example: create an array of IBindable objects, iterate and BindAll to them. Essentially an 'event listener' for all the properties changes of the data set. All the BindAll calls go to the same listener but there is no way to determine which object in the data set has been modified (only the property name, from/to are provided).

I added an origin:IBindable to the BindAll listener that solves this problem, but maybe there is a better solution?

**Comment by profelis** [comment]
No, lazySignal works everywhere, add `-D dump=pretty` and open generated code in dump folder to compare "lazy" behaviour.

I commented here https://github.com/aartzrc/bindx2/commit/f3f87179a61ab7027c537ebbc9914aed489fd1e5
about you changes. 

In general I think you can create BindAllWithOrigin method with you changes (and revert BindAll )) ) and create PR for bindx.

BTW, bindAll are very slow method, because it use reflection. Macro method with same logic will be more fast. Ping me if you catch performance issues in this place.

**Comment by aartzrc** [comment]
Good to know that bindAll is slower. I try to avoid it, but have found a few times it is useful as a starting point to get a project responding quickly - grab everything and filter instead of doing it right :)

Thank you for the comment related to function binding, this is a feature I have not used yet in Haxe but will try to remember in the future.

I'll get a PR to you soon, thanks again!
