### ISSUE TITLE
It can not be compiled with Haxe 4.0.1 ...

### ISSUE THREAD

**Issue by ngrebenshikov** [profelis/bindx2#18]
... because Context.onMacroContextReused is deprecated.

**Comment by profelis** [comment]
Sad news. Haxe again broke good libs with major update. I will try to research fix positivities on weekend

**Comment by ngrebenshikov** [comment]
FYI, commenting using of Context.onMacroContextReused works for me.

**Comment by profelis** [comment]
Maybe you can make PR?

**Comment by profelis** [comment]
And bump version here https://github.com/profelis/bindx2/blob/master/.travis.yml
Maybe :)

**Comment by profelis** [comment]
New version are haxe4 friendly. Some targets fail tests, but it's problem with travis&travix. haxelib update bindx2

**Comment by ngrebenshikov** [comment]
Thank you!
