### ISSUE TITLE
Global binding

### ISSUE THREAD

**Issue by ubald** [profelis/bindx2#6]
Any plans on supporting bindx's bindxGlobal and unbindxGlobal?

**Comment by profelis** [comment]
Plans - no :smile: 
If you really need this feature, I can add it.

**Comment by profelis** [comment]
Done! 2.4.0 version on haxelib
Usage example https://github.com/profelis/bindx2/blob/master/test/BaseTest.hx#L292-L330

**Comment by ubald** [comment]
Well, thanks! I'll try that!

**Comment by ubald** [comment]
It doesn't tell which property was changed though

**Comment by profelis** [comment]
Fixed in master branch. But release only after "fix" php target

**Comment by profelis** [comment]
@ubald done in 2.5.0 release
