### ISSUE TITLE
unbind method

### ISSUE THREAD

**Issue by loudoweb** [profelis/bindx2#7]
How can I unbind after using Bind.bindTo(instance.value, instance2.value) ?

**Comment by profelis** [comment]
bindTo method return unbind callback.

See this code block https://github.com/profelis/bindx2/blob/master/test/BaseTest.hx#L145-L152 for example

**Comment by profelis** [comment]
@loudoweb Thanks for report. I updated readme

**Comment by loudoweb** [comment]
Thank you!
