### ISSUE TITLE
bindAll should provide old and new values like the regular bind method

### ISSUE THREAD

**Issue by ubald** [profelis/bindx2#8]
I'm still trying to replace the old bindx in my project with this one but it is still lacking some features of the previous version.

I quickly tested by modifying line 105 and 109 of BindSignal like this:

```
var listener = function (from, to) callback(name, from, to);
```
```
var listener = function () callback(name, null, null);
```

Thanks for the bindAll though!

**Comment by profelis** [comment]
Can you create push request?

**Comment by profelis** [comment]
fixed in 2.5.1 version

**Comment by ubald** [comment]
wow, that was fast! thanks!

**Comment by profelis** [comment]
Use bindAll very carefully. take a look at BindExt powerfull api, maybe you will found powerful resolution

**Comment by ubald** [comment]
Actually, in my use case, I don’t need binding per se, the only thing I need are notifications when a property changes. That's why the bindAll and the old+new values are important to me. I didn't quite get how BindExt works and what it does.
